CREATE TABLE users (
	id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(110) NOT NULL,
    lastname VARCHAR(110) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password TEXT NOT NULL,
    catalog_name VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY(`id`)
);